### ISSUE TITLE
[BUG] Not Working with NONFULL Waterlogged Blocks!

### ISSUE THREAD

**Issue by itsMarkiS** [mastercake10/CustomOreGen#54]
https://github.com/mastercake10/CustomOreGen/assets/47507632/b02f75b1-60b1-42e1-8c5c-89e9fa9239be

**Comment by mastercake10** [comment]
I don't see how this a bug - water logged blocks always seem to spread water, thus triggering the block forming. I've just verified this with CustomOreGen disabled, its the same behavior.

**Comment by itsMarkiS** [comment]
> I don't see how this a bug - water logged blocks always seem to spread water, thus triggering the block forming. I've just verified this with CustomOreGen disabled, its the same behavior.

the problem is the middle block, the in between the stone stairs and the lava, which is generating cobblestone instead of the custom blocks

**Comment by mastercake10** [comment]
You're right, this is because CustomOreGen still uses the `BlockFromToEvent` and does some weird checks to find out if its cobblestone being generated. There is the `BlockFormEvent` which is much more accurate without all these checkings, but sadly it does not work for bukkit versions =< 1.12.

This means I need to incorporate both events, since 9.8% of CustomOreGen users are still using 1.8.8 :/
